# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"4\n\x0fOutgoingMessage\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x13\n\x0boutgoingMsg\x18\x02 \x01(\x0c\"\x1a\n\nClientInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"D\n\x0bLoginStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x17\n\x0fwelcome_message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xc8\x01\n\x04\x43hat\x12)\n\x0bsendMessage\x12\x10.OutgoingMessage\x1a\x06.Empty\"\x00\x12\x33\n\x0ewaitForMessage\x12\x0b.ClientInfo\x1a\x10.OutgoingMessage\"\x00\x30\x01\x12,\n\x0bloginToChat\x12\x0b.ClientInfo\x1a\x0c.LoginStatus\"\x00\x30\x01\x12\x32\n\rwelcomeClient\x12\x0b.ClientInfo\x1a\x10.OutgoingMessage\"\x00\x30\x01\x62\x06proto3')
)




_OUTGOINGMESSAGE = _descriptor.Descriptor(
  name='OutgoingMessage',
  full_name='OutgoingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='OutgoingMessage.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outgoingMsg', full_name='OutgoingMessage.outgoingMsg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=66,
)


_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ClientInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=94,
)


_LOGINSTATUS = _descriptor.Descriptor(
  name='LoginStatus',
  full_name='LoginStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LoginStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='LoginStatus.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='welcome_message', full_name='LoginStatus.welcome_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=164,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['OutgoingMessage'] = _OUTGOINGMESSAGE
DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['LoginStatus'] = _LOGINSTATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OutgoingMessage = _reflection.GeneratedProtocolMessageType('OutgoingMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTGOINGMESSAGE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:OutgoingMessage)
  ))
_sym_db.RegisterMessage(OutgoingMessage)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTINFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ClientInfo)
  ))
_sym_db.RegisterMessage(ClientInfo)

LoginStatus = _reflection.GeneratedProtocolMessageType('LoginStatus', (_message.Message,), dict(
  DESCRIPTOR = _LOGINSTATUS,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:LoginStatus)
  ))
_sym_db.RegisterMessage(LoginStatus)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=176,
  serialized_end=376,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='Chat.sendMessage',
    index=0,
    containing_service=None,
    input_type=_OUTGOINGMESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='waitForMessage',
    full_name='Chat.waitForMessage',
    index=1,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_OUTGOINGMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='loginToChat',
    full_name='Chat.loginToChat',
    index=2,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_LOGINSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='welcomeClient',
    full_name='Chat.welcomeClient',
    index=3,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_OUTGOINGMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
