# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/Chat/sendMessage',
        request_serializer=chat__pb2.OutgoingMessage.SerializeToString,
        response_deserializer=chat__pb2.Empty.FromString,
        )
    self.waitForMessage = channel.unary_stream(
        '/Chat/waitForMessage',
        request_serializer=chat__pb2.ClientInfo.SerializeToString,
        response_deserializer=chat__pb2.OutgoingMessage.FromString,
        )
    self.loginToChat = channel.unary_stream(
        '/Chat/loginToChat',
        request_serializer=chat__pb2.ClientInfo.SerializeToString,
        response_deserializer=chat__pb2.LoginStatus.FromString,
        )
    self.welcomeClient = channel.unary_stream(
        '/Chat/welcomeClient',
        request_serializer=chat__pb2.ClientInfo.SerializeToString,
        response_deserializer=chat__pb2.OutgoingMessage.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def waitForMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def loginToChat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def welcomeClient(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=chat__pb2.OutgoingMessage.FromString,
          response_serializer=chat__pb2.Empty.SerializeToString,
      ),
      'waitForMessage': grpc.unary_stream_rpc_method_handler(
          servicer.waitForMessage,
          request_deserializer=chat__pb2.ClientInfo.FromString,
          response_serializer=chat__pb2.OutgoingMessage.SerializeToString,
      ),
      'loginToChat': grpc.unary_stream_rpc_method_handler(
          servicer.loginToChat,
          request_deserializer=chat__pb2.ClientInfo.FromString,
          response_serializer=chat__pb2.LoginStatus.SerializeToString,
      ),
      'welcomeClient': grpc.unary_stream_rpc_method_handler(
          servicer.welcomeClient,
          request_deserializer=chat__pb2.ClientInfo.FromString,
          response_serializer=chat__pb2.OutgoingMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
