# Spartan Server Port
port: 3000

# LRU cache
max_num_messages_per_user: 5

# Rate limit
max_call_per_30_seconds_per_user: 3

# 1-1 messaging
users: [alice,bob,charlie,eve,foo,bar,baz,qux]

# Group messaging
groups:
 group1: [alice,bob,charlie,eve]
 group2: [foo,bar,baz,qux]

encryptionkey: '56E094D42D03B70A1B22F0CFC08FCBF0'
phrase: 'Something common'
